### ISSUE TITLE
Error in filename in index.js

### ISSUE THREAD

**Issue by nrigaudiere** [pqml/raf#1]
This error pops when loading `index.js` on a Linux environment.
There is no issue on MacOSX because it does not care about files names being caps locked or not.

```
Error: ./node_modules/@internet/raf/lib/index.js
  Module not found: Error: Can't resolve './FpsLimiter.js' in '/usr/src/app/node  _modules/@internet/raf/lib'
  resolve './FpsLimiter.js' in '/usr/src/app/node_modules/@internet/raf/lib'
```

**Comment by pqml** [comment]
Ouch... sorry about that

**Comment by pqml** [comment]
@nrigaudiere I also published a new version on npm with your fix
